sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Root
  gcs:
    endpoint: https://storage.googleapis.com
    bucket-name: sky-itcast
    service-account-json: ${GOOGLE_APPLICATION_CREDENTIALS}c
  redis:
    host: localhost
    port: 6379

    database: 10
